### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by silverwind** [hendrikw01/tr-064#1]
Nice library, been playing around with it and it works quite well!

Do you plan on adding support for authentication, as seen in Section 10.7 of AVM's docs?

**Comment by JumpLink** [comment]
+1

**Comment by HWiese1980** [comment]
+1

**Comment by hendrikw01** [comment]
Authentication is now supported

**Comment by HWiese1980** [comment]
Appreciated! Thanks!

**Comment by JumpLink** [comment]
Thanks!
